apiVersion: v1
kind: Service
metadata:
  name: loc-service
spec:
  selector:
    app: trading-platform
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: trade-exchange-service
spec:
  selector:
    app: trading-platform
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: trading-platform
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    app: trading-platform
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
