version: '3.9'
services:
  loc-service:
    build: ./loc-service
    ports:
      - "8001:8000"
  finance-service:
    build: ./finance-service
    ports:
      - "8002:8000"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
